// Translation strings for FieldFlow — 20 languages
export type Lang = 'en' | 'es' | 'fr' | 'pt' | 'de' | 'zh' | 'ja' | 'ar' | 'hi' | 'ko' | 'it' | 'nl' | 'pl' | 'tr' | 'vi' | 'th' | 'sv' | 'da' | 'no' | 'fi';

export const languageNames: Record<Lang, string> = {
  en: 'English', es: 'Español', fr: 'Français', pt: 'Português', de: 'Deutsch',
  zh: '中文', ja: '日本語', ar: 'العربية', hi: 'हिन्दी', ko: '한국어',
  it: 'Italiano', nl: 'Nederlands', pl: 'Polski', tr: 'Türkçe', vi: 'Tiếng Việt',
  th: 'ไทย', sv: 'Svenska', da: 'Dansk', no: 'Norsk', fi: 'Suomi',
};

type T = Record<string, Record<Lang, string>>;

export const t: T = {
  // Navigation
  'nav.home':        { en:'Home', es:'Inicio', fr:'Accueil', pt:'Início', de:'Start', zh:'首页', ja:'ホーム', ar:'الرئيسية', hi:'होम', ko:'홈', it:'Home', nl:'Home', pl:'Główna', tr:'Ana Sayfa', vi:'Trang chủ', th:'หน้าแรก', sv:'Hem', da:'Hjem', no:'Hjem', fi:'Koti' },
  'nav.calendar':    { en:'Calendar', es:'Calendario', fr:'Calendrier', pt:'Calendário', de:'Kalender', zh:'日历', ja:'カレンダー', ar:'التقويم', hi:'कैलेंडर', ko:'캘린더', it:'Calendario', nl:'Kalender', pl:'Kalendarz', tr:'Takvim', vi:'Lịch', th:'ปฏิทิน', sv:'Kalender', da:'Kalender', no:'Kalender', fi:'Kalenteri' },
  'nav.jobs':        { en:'Jobs', es:'Trabajos', fr:'Travaux', pt:'Trabalhos', de:'Aufträge', zh:'工作', ja:'ジョブ', ar:'المهام', hi:'कार्य', ko:'작업', it:'Lavori', nl:'Klussen', pl:'Zlecenia', tr:'İşler', vi:'Công việc', th:'งาน', sv:'Jobb', da:'Job', no:'Jobber', fi:'Työt' },
  'nav.quotes':      { en:'Quotes', es:'Presupuestos', fr:'Devis', pt:'Orçamentos', de:'Angebote', zh:'报价', ja:'見積もり', ar:'عروض الأسعار', hi:'कोटेशन', ko:'견적', it:'Preventivi', nl:'Offertes', pl:'Wyceny', tr:'Teklifler', vi:'Báo giá', th:'ใบเสนอราคา', sv:'Offerter', da:'Tilbud', no:'Tilbud', fi:'Tarjoukset' },
  'nav.invoices':    { en:'Invoices', es:'Facturas', fr:'Factures', pt:'Faturas', de:'Rechnungen', zh:'发票', ja:'請求書', ar:'الفواتير', hi:'चालान', ko:'청구서', it:'Fatture', nl:'Facturen', pl:'Faktury', tr:'Faturalar', vi:'Hóa đơn', th:'ใบแจ้งหนี้', sv:'Fakturor', da:'Fakturaer', no:'Fakturaer', fi:'Laskut' },
  'nav.more':        { en:'More', es:'Más', fr:'Plus', pt:'Mais', de:'Mehr', zh:'更多', ja:'もっと', ar:'المزيد', hi:'और', ko:'더보기', it:'Altro', nl:'Meer', pl:'Więcej', tr:'Daha Fazla', vi:'Thêm', th:'เพิ่มเติม', sv:'Mer', da:'Mere', no:'Mer', fi:'Lisää' },
  'nav.settings':    { en:'Settings', es:'Ajustes', fr:'Paramètres', pt:'Configurações', de:'Einstellungen', zh:'设置', ja:'設定', ar:'الإعدادات', hi:'सेटिंग्स', ko:'설정', it:'Impostazioni', nl:'Instellingen', pl:'Ustawienia', tr:'Ayarlar', vi:'Cài đặt', th:'การตั้งค่า', sv:'Inställningar', da:'Indstillinger', no:'Innstillinger', fi:'Asetukset' },

  // Dashboard
  'dash.revenue':     { en:'Revenue', es:'Ingresos', fr:'Revenu', pt:'Receita', de:'Umsatz', zh:'收入', ja:'収益', ar:'الإيرادات', hi:'राजस्व', ko:'수익', it:'Ricavi', nl:'Omzet', pl:'Przychody', tr:'Gelir', vi:'Doanh thu', th:'รายได้', sv:'Intäkter', da:'Indtægter', no:'Inntekter', fi:'Tulot' },
  'dash.profit':      { en:'Profit', es:'Ganancia', fr:'Bénéfice', pt:'Lucro', de:'Gewinn', zh:'利润', ja:'利益', ar:'الربح', hi:'लाभ', ko:'이익', it:'Profitto', nl:'Winst', pl:'Zysk', tr:'Kâr', vi:'Lợi nhuận', th:'กำไร', sv:'Vinst', da:'Fortjeneste', no:'Fortjeneste', fi:'Voitto' },
  'dash.activeJobs':  { en:'Active Jobs', es:'Trabajos Activos', fr:'Travaux Actifs', pt:'Trabalhos Ativos', de:'Aktive Aufträge', zh:'进行中的工作', ja:'進行中のジョブ', ar:'المهام النشطة', hi:'सक्रिय कार्य', ko:'진행 중 작업', it:'Lavori Attivi', nl:'Actieve Klussen', pl:'Aktywne Zlecenia', tr:'Aktif İşler', vi:'Công việc đang làm', th:'งานที่กำลังทำ', sv:'Aktiva Jobb', da:'Aktive Job', no:'Aktive Jobber', fi:'Aktiiviset Työt' },
  'dash.openQuotes':  { en:'Open Quotes', es:'Presupuestos Abiertos', fr:'Devis Ouverts', pt:'Orçamentos Abertos', de:'Offene Angebote', zh:'待处理报价', ja:'未処理の見積もり', ar:'عروض الأسعار المفتوحة', hi:'खुले कोटेशन', ko:'미결 견적', it:'Preventivi Aperti', nl:'Open Offertes', pl:'Otwarte Wyceny', tr:'Açık Teklifler', vi:'Báo giá đang chờ', th:'ใบเสนอราคาที่เปิดอยู่', sv:'Öppna Offerter', da:'Åbne Tilbud', no:'Åpne Tilbud', fi:'Avoimet Tarjoukset' },
  'dash.customers':   { en:'Customers', es:'Clientes', fr:'Clients', pt:'Clientes', de:'Kunden', zh:'客户', ja:'顧客', ar:'العملاء', hi:'ग्राहक', ko:'고객', it:'Clienti', nl:'Klanten', pl:'Klienci', tr:'Müşteriler', vi:'Khách hàng', th:'ลูกค้า', sv:'Kunder', da:'Kunder', no:'Kunder', fi:'Asiakkaat' },
  'dash.quickActions':{ en:'Quick Actions', es:'Acciones Rápidas', fr:'Actions Rapides', pt:'Ações Rápidas', de:'Schnellaktionen', zh:'快捷操作', ja:'クイックアクション', ar:'إجراءات سريعة', hi:'त्वरित कार्रवाई', ko:'빠른 작업', it:'Azioni Rapide', nl:'Snelle Acties', pl:'Szybkie Akcje', tr:'Hızlı İşlemler', vi:'Thao tác nhanh', th:'การดำเนินการด่วน', sv:'Snabbåtgärder', da:'Hurtigvalg', no:'Hurtigvalg', fi:'Pikatoiminnot' },
  'dash.newQuote':    { en:'New Quote', es:'Nuevo Presupuesto', fr:'Nouveau Devis', pt:'Novo Orçamento', de:'Neues Angebot', zh:'新建报价', ja:'新規見積もり', ar:'عرض سعر جديد', hi:'नया कोटेशन', ko:'새 견적', it:'Nuovo Preventivo', nl:'Nieuwe Offerte', pl:'Nowa Wycena', tr:'Yeni Teklif', vi:'Tạo báo giá', th:'สร้างใบเสนอราคา', sv:'Ny Offert', da:'Nyt Tilbud', no:'Nytt Tilbud', fi:'Uusi Tarjous' },
  'dash.newJob':      { en:'New Job', es:'Nuevo Trabajo', fr:'Nouveau Travail', pt:'Novo Trabalho', de:'Neuer Auftrag', zh:'新建工作', ja:'新規ジョブ', ar:'مهمة جديدة', hi:'नया कार्य', ko:'새 작업', it:'Nuovo Lavoro', nl:'Nieuwe Klus', pl:'Nowe Zlecenie', tr:'Yeni İş', vi:'Tạo công việc', th:'สร้างงาน', sv:'Nytt Jobb', da:'Nyt Job', no:'Nytt Jobb', fi:'Uusi Työ' },
  'dash.newInvoice':  { en:'New Invoice', es:'Nueva Factura', fr:'Nouvelle Facture', pt:'Nova Fatura', de:'Neue Rechnung', zh:'新建发票', ja:'新規請求書', ar:'فاتورة جديدة', hi:'नया चालान', ko:'새 청구서', it:'Nuova Fattura', nl:'Nieuwe Factuur', pl:'Nowa Faktura', tr:'Yeni Fatura', vi:'Tạo hóa đơn', th:'สร้างใบแจ้งหนี้', sv:'Ny Faktura', da:'Ny Faktura', no:'Ny Faktura', fi:'Uusi Lasku' },

  // Common
  'common.save':      { en:'Save', es:'Guardar', fr:'Enregistrer', pt:'Salvar', de:'Speichern', zh:'保存', ja:'保存', ar:'حفظ', hi:'सहेजें', ko:'저장', it:'Salva', nl:'Opslaan', pl:'Zapisz', tr:'Kaydet', vi:'Lưu', th:'บันทึก', sv:'Spara', da:'Gem', no:'Lagre', fi:'Tallenna' },
  'common.cancel':    { en:'Cancel', es:'Cancelar', fr:'Annuler', pt:'Cancelar', de:'Abbrechen', zh:'取消', ja:'キャンセル', ar:'إلغاء', hi:'रद्द करें', ko:'취소', it:'Annulla', nl:'Annuleren', pl:'Anuluj', tr:'İptal', vi:'Hủy', th:'ยกเลิก', sv:'Avbryt', da:'Annuller', no:'Avbryt', fi:'Peruuta' },
  'common.delete':    { en:'Delete', es:'Eliminar', fr:'Supprimer', pt:'Excluir', de:'Löschen', zh:'删除', ja:'削除', ar:'حذف', hi:'हटाएं', ko:'삭제', it:'Elimina', nl:'Verwijderen', pl:'Usuń', tr:'Sil', vi:'Xóa', th:'ลบ', sv:'Ta bort', da:'Slet', no:'Slett', fi:'Poista' },
  'common.edit':      { en:'Edit', es:'Editar', fr:'Modifier', pt:'Editar', de:'Bearbeiten', zh:'编辑', ja:'編集', ar:'تعديل', hi:'संपादित करें', ko:'편집', it:'Modifica', nl:'Bewerken', pl:'Edytuj', tr:'Düzenle', vi:'Sửa', th:'แก้ไข', sv:'Redigera', da:'Rediger', no:'Rediger', fi:'Muokkaa' },
  'common.add':       { en:'Add', es:'Agregar', fr:'Ajouter', pt:'Adicionar', de:'Hinzufügen', zh:'添加', ja:'追加', ar:'إضافة', hi:'जोड़ें', ko:'추가', it:'Aggiungi', nl:'Toevoegen', pl:'Dodaj', tr:'Ekle', vi:'Thêm', th:'เพิ่ม', sv:'Lägg till', da:'Tilføj', no:'Legg til', fi:'Lisää' },
  'common.back':      { en:'Back', es:'Atrás', fr:'Retour', pt:'Voltar', de:'Zurück', zh:'返回', ja:'戻る', ar:'رجوع', hi:'वापस', ko:'뒤로', it:'Indietro', nl:'Terug', pl:'Wstecz', tr:'Geri', vi:'Quay lại', th:'กลับ', sv:'Tillbaka', da:'Tilbage', no:'Tilbake', fi:'Takaisin' },
  'common.yes':       { en:'Yes', es:'Sí', fr:'Oui', pt:'Sim', de:'Ja', zh:'是', ja:'はい', ar:'نعم', hi:'हाँ', ko:'예', it:'Sì', nl:'Ja', pl:'Tak', tr:'Evet', vi:'Có', th:'ใช่', sv:'Ja', da:'Ja', no:'Ja', fi:'Kyllä' },
  'common.no':        { en:'No', es:'No', fr:'Non', pt:'Não', de:'Nein', zh:'否', ja:'いいえ', ar:'لا', hi:'नहीं', ko:'아니요', it:'No', nl:'Nee', pl:'Nie', tr:'Hayır', vi:'Không', th:'ไม่', sv:'Nej', da:'Nej', no:'Nei', fi:'Ei' },
  'common.loading':   { en:'Loading...', es:'Cargando...', fr:'Chargement...', pt:'Carregando...', de:'Laden...', zh:'加载中...', ja:'読み込み中...', ar:'جاري التحميل...', hi:'लोड हो रहा है...', ko:'로딩 중...', it:'Caricamento...', nl:'Laden...', pl:'Ładowanie...', tr:'Yükleniyor...', vi:'Đang tải...', th:'กำลังโหลด...', sv:'Laddar...', da:'Indlæser...', no:'Laster...', fi:'Ladataan...' },
  'common.name':      { en:'Name', es:'Nombre', fr:'Nom', pt:'Nome', de:'Name', zh:'名称', ja:'名前', ar:'الاسم', hi:'नाम', ko:'이름', it:'Nome', nl:'Naam', pl:'Nazwa', tr:'İsim', vi:'Tên', th:'ชื่อ', sv:'Namn', da:'Navn', no:'Navn', fi:'Nimi' },
  'common.status':    { en:'Status', es:'Estado', fr:'Statut', pt:'Status', de:'Status', zh:'状态', ja:'ステータス', ar:'الحالة', hi:'स्थिति', ko:'상태', it:'Stato', nl:'Status', pl:'Status', tr:'Durum', vi:'Trạng thái', th:'สถานะ', sv:'Status', da:'Status', no:'Status', fi:'Tila' },
  'common.total':     { en:'Total', es:'Total', fr:'Total', pt:'Total', de:'Gesamt', zh:'总计', ja:'合計', ar:'المجموع', hi:'कुल', ko:'합계', it:'Totale', nl:'Totaal', pl:'Suma', tr:'Toplam', vi:'Tổng', th:'รวม', sv:'Total', da:'Total', no:'Total', fi:'Yhteensä' },
  'common.due':       { en:'Due', es:'Pendiente', fr:'Dû', pt:'Devido', de:'Offen', zh:'到期', ja:'支払い期日', ar:'مستحق', hi:'देय', ko:'미지급', it:'Dovuto', nl:'Verschuldigd', pl:'Należne', tr:'Vadesi Dolan', vi:'Còn nợ', th:'ครบกำหนด', sv:'Förfallet', da:'Forfaldet', no:'Forfalt', fi:'Erääntynyt' },

  // Settings
  'settings.language':    { en:'Language', es:'Idioma', fr:'Langue', pt:'Idioma', de:'Sprache', zh:'语言', ja:'言語', ar:'اللغة', hi:'भाषा', ko:'언어', it:'Lingua', nl:'Taal', pl:'Język', tr:'Dil', vi:'Ngôn ngữ', th:'ภาษา', sv:'Språk', da:'Sprog', no:'Språk', fi:'Kieli' },
  'settings.branding':    { en:'Branding', es:'Marca', fr:'Image de marque', pt:'Marca', de:'Branding', zh:'品牌', ja:'ブランディング', ar:'العلامة التجارية', hi:'ब्रांडिंग', ko:'브랜딩', it:'Marchio', nl:'Branding', pl:'Marka', tr:'Marka', vi:'Thương hiệu', th:'แบรนด์', sv:'Varumärke', da:'Brand', no:'Merkevare', fi:'Brändi' },
  'settings.integrations':{ en:'Integrations', es:'Integraciones', fr:'Intégrations', pt:'Integrações', de:'Integrationen', zh:'集成', ja:'連携', ar:'التكاملات', hi:'एकीकरण', ko:'통합', it:'Integrazioni', nl:'Integraties', pl:'Integracje', tr:'Entegrasyonlar', vi:'Tích hợp', th:'การเชื่อมต่อ', sv:'Integrationer', da:'Integrationer', no:'Integrasjoner', fi:'Integraatiot' },
  'settings.data':        { en:'Data', es:'Datos', fr:'Données', pt:'Dados', de:'Daten', zh:'数据', ja:'データ', ar:'البيانات', hi:'डेटा', ko:'데이터', it:'Dati', nl:'Gegevens', pl:'Dane', tr:'Veriler', vi:'Dữ liệu', th:'ข้อมูล', sv:'Data', da:'Data', no:'Data', fi:'Tiedot' },

  // Onboarding
  'onboarding.welcome':     { en:'Welcome to FieldFlow', es:'Bienvenido a FieldFlow', fr:'Bienvenue sur FieldFlow', pt:'Bem-vindo ao FieldFlow', de:'Willkommen bei FieldFlow', zh:'欢迎使用 FieldFlow', ja:'FieldFlow へようこそ', ar:'مرحباً بك في FieldFlow', hi:'FieldFlow में आपका स्वागत है', ko:'FieldFlow에 오신 것을 환영합니다', it:'Benvenuto in FieldFlow', nl:'Welkom bij FieldFlow', pl:'Witamy w FieldFlow', tr:'FieldFlow\u2019a Hoş Geldiniz', vi:'Chào mừng đến với FieldFlow', th:'ยินดีต้อนรับสู่ FieldFlow', sv:'Välkommen till FieldFlow', da:'Velkommen til FieldFlow', no:'Velkommen til FieldFlow', fi:'Tervetuloa FieldFlow:iin' },
  'onboarding.subtitle':    { en:'The business OS for service businesses', es:'El sistema operativo para negocios de servicios', fr:'Le système d\u2019exploitation pour les entreprises de services', pt:'O SO para empresas de serviços', de:'Das Betriebssystem für Dienstleistungsunternehmen', zh:'服务行业的商业操作系统', ja:'サービス業のためのビジネスOS', ar:'نظام التشغيل لأعمال الخدمات', hi:'सेवा व्यवसायों के लिए व्यावसायिक OS', ko:'서비스 비즈니스를 위한 비즈니스 OS', it:'Il SO per le aziende di servizi', nl:'Het besturingssysteem voor dienstverleners', pl:'System dla firm usługowych', tr:'Hizmet işletmeleri için işletim sistemi', vi:'Hệ điều hành cho doanh nghiệp dịch vụ', th:'ระบบปฏิบัติการสำหรับธุรกิจบริการ', sv:'OS för tjänsteföretag', da:'OS for servicevirksomheder', no:'OS for tjenestevirksomheter', fi:'Palveluyritysten käyttöjärjestelmä' },
  'onboarding.getStarted':  { en:'Get Started', es:'Comenzar', fr:'Commencer', pt:'Começar', de:'Loslegen', zh:'开始使用', ja:'始める', ar:'ابدأ', hi:'शुरू करें', ko:'시작하기', it:'Inizia', nl:'Aan de slag', pl:'Rozpocznij', tr:'Başla', vi:'Bắt đầu', th:'เริ่มต้น', sv:'Kom igång', da:'Kom i gang', no:'Kom i gang', fi:'Aloita' },
  'onboarding.businessName':{ en:"What's your business name?", es:'¿Cuál es el nombre de tu negocio?', fr:'Quel est le nom de votre entreprise?', pt:'Qual é o nome da sua empresa?', de:'Wie heißt Ihr Unternehmen?', zh:'你的公司名称是什么？', ja:'あなたの事業名は何ですか？', ar:'ما اسم شركتك؟', hi:'आपके व्यवसाय का नाम क्या है?', ko:'사업체 이름이 무엇입니까?', it:'Qual è il nome della tua azienda?', nl:'Wat is de naam van uw bedrijf?', pl:'Jaka jest nazwa Twojej firmy?', tr:'İşletme adınız ne?', vi:'Tên doanh nghiệp của bạn là gì?', th:'ชื่อธุรกิจของคุณคืออะไร?', sv:'Vad heter ditt företag?', da:'Hvad hedder din virksomhed?', no:'Hva heter bedriften din?', fi:'Mikä on yrityksesi nimi?' },
  'onboarding.industry':    { en:'What industry?', es:'¿Qué industria?', fr:'Quelle industrie?', pt:'Qual setor?', de:'Welche Branche?', zh:'哪个行业？', ja:'どの業界ですか？', ar:'ما المجال؟', hi:'कौन सा उद्योग?', ko:'어떤 업종입니까?', it:'Quale settore?', nl:'Welke branche?', pl:'Jaka branża?', tr:'Hangi sektör?', vi:'Ngành nghề nào?', th:'อุตสาหกรรมอะไร?', sv:'Vilken bransch?', da:'Hvilken branche?', no:'Hvilken bransje?', fi:'Mikä ala?' },
  'onboarding.startBuilding':{ en:'Start Building', es:'Empezar a Construir', fr:'Commencer à Construire', pt:'Começar a Construir', de:'Loslegen', zh:'开始构建', ja:'構築を始める', ar:'ابدأ البناء', hi:'बनाना शुरू करें', ko:'구축 시작', it:'Inizia a Costruire', nl:'Begin met Bouwen', pl:'Zacznij Budować', tr:'İnşa Et', vi:'Bắt đầu xây dựng', th:'เริ่มสร้าง', sv:'Börja Bygga', da:'Begynd at Bygge', no:'Begynn å Bygge', fi:'Aloita Rakentaminen' },

  // Misc
  'misc.offline':       { en:"You're offline \u2014 changes will sync when reconnected", es:'Sin conexión \u2014 los cambios se sincronizarán al reconectar', fr:'Hors ligne \u2014 les modifications seront synchronisées à la reconnexion', pt:'Offline \u2014 as alterações serão sincronizadas ao reconectar', de:'Offline \u2014 Änderungen werden bei Wiederverbindung synchronisiert', zh:'离线 \u2014 重新连接后将同步更改', ja:'オフライン \u2014 再接続時に変更が同期されます', ar:'غير متصل \u2014 ستتم المزامنة عند إعادة الاتصال', hi:'ऑफलाइन \u2014 पुनः कनेक्ट होने पर परिवर्तन सिंक होंगे', ko:'오프라인 \u2014 다시 연결되면 변경 사항이 동기화됩니다', it:'Offline \u2014 le modifiche verranno sincronizzate alla riconnessione', nl:'Offline \u2014 wijzigingen worden gesynchroniseerd bij herverbinding', pl:'Offline \u2014 zmiany zostaną zsynchronizowane po ponownym połączeniu', tr:'Çevrimdışı \u2014 yeniden bağlanıldığında değişiklikler senkronize edilecek', vi:'Ngoại tuyến \u2014 thay đổi sẽ đồng bộ khi kết nối lại', th:'ออฟไลน์ \u2014 การเปลี่ยนแปลงจะซิงค์เมื่อเชื่อมต่อใหม่', sv:'Offline \u2014 ändringar synkroniseras vid återanslutning', da:'Offline \u2014 ændringer synkroniseres ved genopkobling', no:'Offline \u2014 endringer synkroniseres ved gjenoppretting', fi:'Offline \u2014 muutokset synkronoidaan uudelleen yhdistettäessä' },
  'misc.welcomeBack':   { en:'Welcome back', es:'Bienvenido de vuelta', fr:'Bon retour', pt:'Bem-vindo de volta', de:'Willkommen zurück', zh:'欢迎回来', ja:'おかえりなさい', ar:'مرحباً بعودتك', hi:'वापसी पर स्वागत', ko:'다시 오신 것을 환영합니다', it:'Bentornato', nl:'Welkom terug', pl:'Witamy ponownie', tr:'Tekrar hoş geldiniz', vi:'Chào mừng trở lại', th:'ยินดีต้อนรับกลับ', sv:'Välkommen tillbaka', da:'Velkommen tilbage', no:'Velkommen tilbake', fi:'Tervetuloa takaisin' },
};

export function translate(key: string, lang: Lang): string {
  return t[key]?.[lang] || t[key]?.['en'] || key;
}
