import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../store/AppContext';
import { Quote, QuoteLineItem } from '../types';
import { industryTemplates } from '../data/templates';
import { v4 as uuid } from 'uuid';

export default function SmartQuote() {
  const navigate = useNavigate();
  const { settings, quotes, customers, dispatch } = useApp();
  const [description, setDescription] = useState('');
  const [selectedCustomerId, setSelectedCustomerId] = useState('');
  const [generated, setGenerated] = useState<Quote | null>(null);
  const [analyzing, setAnalyzing] = useState(false);

  const template = industryTemplates.find(t => t.id === settings.industry) || industryTemplates[industryTemplates.length - 1];

  function generateQuote() {
    if (!description.trim()) return;
    setAnalyzing(true);

    // Simulate AI analysis delay
    setTimeout(() => {
      // Parse the description for line items using industry templates + pattern matching
      const lineItems: QuoteLineItem[] = [];
      const desc = description.toLowerCase();

      // Match against template defaults
      template.quoteLineItemDefaults.forEach(tmpl => {
        const keywords = tmpl.description.toLowerCase().split(/[\s/]+/);
        const match = keywords.some(kw => kw.length > 2 && desc.includes(kw));
        if (match) {
          lineItems.push({
            id: uuid(),
            description: tmpl.description,
            quantity: 1,
            unitPrice: tmpl.unitPrice,
            cost: tmpl.cost,
          });
        }
      });

      // If no matches, create generic items based on common patterns
      if (lineItems.length === 0) {
        // Try to extract quantities and items from natural language
        const qtyPatterns = desc.match(/(\d+)\s*(cabinet|door|window|room|fixture|outlet|switch|faucet|toilet|sink|appliance|light|fan|unit|piece|hour|day|foot|feet|yard|gallon|sheet|box)/gi);
        if (qtyPatterns) {
          qtyPatterns.forEach(match => {
            const parts = match.match(/(\d+)\s*(.+)/i);
            if (parts) {
              lineItems.push({
                id: uuid(),
                description: `${parts[2].charAt(0).toUpperCase() + parts[2].slice(1)} (service)`,
                quantity: parseInt(parts[1]),
                unitPrice: 100,
                cost: 40,
              });
            }
          });
        }

        // Fallback: use template defaults as-is
        if (lineItems.length === 0) {
          template.quoteLineItemDefaults.forEach(tmpl => {
            lineItems.push({
              id: uuid(),
              description: tmpl.description,
              quantity: 1,
              unitPrice: tmpl.unitPrice,
              cost: tmpl.cost,
            });
          });
        }
      }

      // Calculate win probability based on past quotes
      const acceptedCount = quotes.filter(q => q.status === 'accepted').length;
      const totalCount = quotes.filter(q => q.status !== 'draft').length || 1;
      const baseRate = acceptedCount / totalCount;
      const cust = customers.find(c => c.id === selectedCustomerId);
      const hasHistory = cust && quotes.some(q => q.customerId === cust.id && q.status === 'accepted');
      const winProb = Math.min(0.95, Math.max(0.1, baseRate + (hasHistory ? 0.2 : 0) + (lineItems.length > 2 ? -0.1 : 0.05)));

      const quote: Quote = {
        id: uuid(),
        customerId: selectedCustomerId,
        customerName: cust?.name || '',
        title: description.slice(0, 80),
        description,
        lineItems,
        taxRate: settings.taxRate,
        status: 'draft',
        validUntil: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
        notes: `Generated by Smart Quote on ${new Date().toLocaleDateString()}`,
        winProbability: Math.round(winProb * 100),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      setGenerated(quote);
      setAnalyzing(false);
    }, 800);
  }

  function saveQuote() {
    if (!generated) return;
    dispatch({ type: 'ADD_QUOTE', payload: generated });
    navigate(`/quotes/${generated.id}`);
  }

  const subtotal = generated?.lineItems.reduce((s, li) => s + li.quantity * li.unitPrice, 0) || 0;
  const tax = subtotal * ((generated?.taxRate || 0) / 100);
  const total = subtotal + tax;
  const totalCost = generated?.lineItems.reduce((s, li) => s + li.quantity * li.cost, 0) || 0;
  const profit = subtotal - totalCost;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold">🧠 Smart Quote</h2>
      </div>

      <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
        <p className="text-slate-400 text-sm mb-3">Describe the job in your own words. AI will generate a quote with line items, pricing, and profit estimates based on your {template.name} template and past quotes.</p>

        <select className="w-full bg-slate-800 rounded-lg px-3 py-2 text-sm border border-slate-700 focus:border-brand-500 focus:outline-none mb-3" value={selectedCustomerId} onChange={e => setSelectedCustomerId(e.target.value)}>
          <option value="">Select customer (optional)</option>
          {customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>

        <textarea
          className="w-full bg-slate-800 rounded-lg px-3 py-3 text-sm border border-slate-700 focus:border-brand-500 focus:outline-none"
          placeholder={`e.g. "Replace 3 faucets in the bathroom and install a new garbage disposal in the kitchen"`}
          rows={4}
          value={description}
          onChange={e => setDescription(e.target.value)}
        />

        <button onClick={generateQuote} disabled={!description.trim() || analyzing} className="w-full mt-3 bg-brand-600 hover:bg-brand-700 disabled:opacity-50 text-white rounded-lg py-3 font-medium transition-colors flex items-center justify-center gap-2">
          {analyzing ? (
            <>
              <span className="animate-spin">⏳</span>
              <span>Analyzing...</span>
            </>
          ) : (
            <>
              <span>🧠</span>
              <span>Generate Quote</span>
            </>
          )}
        </button>
      </div>

      {/* Generated quote preview */}
      {generated && (
        <div className="space-y-4">
          {/* Win probability */}
          <div className="bg-slate-900 rounded-xl p-4 border border-slate-800">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm text-slate-400">Win Probability</span>
              <span className={`text-lg font-bold ${
                (generated.winProbability || 0) >= 70 ? 'text-emerald-400' :
                (generated.winProbability || 0) >= 40 ? 'text-amber-400' : 'text-red-400'
              }`}>{generated.winProbability || 0}%</span>
            </div>
            <div className="w-full bg-slate-800 rounded-full h-2">
              <div
                className={`rounded-full h-2 transition-all ${
                  (generated.winProbability || 0) >= 70 ? 'bg-emerald-500' :
                  (generated.winProbability || 0) >= 40 ? 'bg-amber-500' : 'bg-red-500'
                }`}
                style={{ width: `${generated.winProbability || 0}%` }}
              />
            </div>
            {(generated.winProbability || 0) < 50 && (
              <p className="text-xs text-slate-500 mt-1">Tip: Returning customers have a 20% higher close rate. Consider following up personally.</p>
            )}
          </div>

          {/* Line items */}
          <div className="bg-slate-900 rounded-lg p-4 border border-slate-800">
            <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-3">Generated Line Items</h3>
            <div className="space-y-2">
              {generated.lineItems.map((li, i) => (
                <div key={li.id} className="flex items-center justify-between text-sm">
                  <span className="text-slate-300">{i + 1}. {li.description} × {li.quantity}</span>
                  <span className="font-medium">${(li.quantity * li.unitPrice).toFixed(2)}</span>
                </div>
              ))}
            </div>
            <div className="border-t border-slate-700 mt-3 pt-3 space-y-1">
              <div className="flex justify-between text-sm"><span className="text-slate-400">Subtotal</span><span>${subtotal.toFixed(2)}</span></div>
              <div className="flex justify-between text-sm"><span className="text-slate-400">Tax ({generated.taxRate}%)</span><span>${tax.toFixed(2)}</span></div>
              <div className="flex justify-between text-lg font-bold"><span>Total</span><span>${total.toFixed(2)}</span></div>
              <div className="flex justify-between text-sm"><span className="text-slate-400">Est. Profit</span><span className={profit >= 0 ? 'text-emerald-400' : 'text-red-400'}>${profit.toFixed(2)}</span></div>
            </div>
          </div>

          <div className="flex gap-3">
            <button onClick={saveQuote} className="flex-1 bg-brand-600 hover:bg-brand-700 text-white rounded-lg py-3 font-medium">
              Save & Edit Quote
            </button>
            <button onClick={() => setGenerated(null)} className="flex-1 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg py-3">
              Try Again
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
